account/urls.py
from django.conf.urls import url
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:form_id>/', views.show, name='show'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from snsProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models


class Data(models.Model):
    name = models.CharField(max_length=30)
    text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.name


class Photo(models.Model):
    data = models.ForeignKey(Data, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from account.models import Data, Photo


def index(request):
    if request.method == "POST":
        form = Data()
        form.name = request.POST["name"]
        form.text = request.POST["text"]
        form.pub_date = timezone.datetime.now()
        form.save()
        for img in request.FILES.getlist('images'):
            photo = Photo()
            photo.data = form
            photo.image = img
            photo.save()
        return redirect('show/' + str(form.id), form.id)
    else:
        return render(request, 'index.html')


def show(request, form_id):
    lst = get_object_or_404(Data, pk=form_id)
    return render(request, 'show.html', {'lst': lst})

account/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'account:index' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    이름 : <input type="text" name="name" > <br>
    내용 : <input type="text" name="text" > <br>
    사진 : <input type="file" name="images" multiple> <br>
    <input type="submit" value="전송"> <br>
</form>
</body>
</html>

account/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% csrf_token %}
    {% if lst %}
    {% for x in lst.photo_set.all %}
        id : &nbsp {{ x.data.id }} <br>
        이름 : &nbsp {{ x.data.name }} <br>
        내용 : &nbsp {{ x.data.text }} <br>
        <img src="{{x.image.url}}" ><br>
    {% endfor %}
    {% endif %}
</body>
</html>