account/urls.py
from django.conf.urls import url
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:form_id>/', views.show, name='show'),
]

accountapp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

profileapp/urls.py
from django.urls import path
from profileapp import views
from profileapp.views import ProfileCreateView, ProfileUpdateView


app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from snsProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm


has_decorator = [login_required, account_ownership_required]


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:main')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


'''
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
'''


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:main')
    template_name = 'accountapp/update.html'


'''
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()
'''


'''
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
'''


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'


'''
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()
'''


def success(request):
    return render(request, 'success.html')


@login_required
def main(request):
    return render(request, 'accountapp/main.html')


'''
def main(request):
    if request.user.is_authenticated:
        return render(request, 'main.html')
    else:
        return HttpResponseRedirect(reverse('accountapp:login'))
'''

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4> 회원가입 </h4>
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h6 style="font-size: 12px"> 회원탈퇴를 원하시면 탈퇴버튼을 클릭하세요. </h6>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {{ form }}
            <p></p>
            <input type="submit" value="탈퇴" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block contents %}
<div>
    <div style="text-align:center">
        <p>
           {{ target_user.date_joined }}
        </p>

        {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="" style="height: 8rem; width: 8rem; border-radius: 10rem; margin-bottom: .5rem;">
            <h5 style="font-family: 'NanumGothic'">
                {{ target_user.profile.nickname }}
                {% if target_user.profile == user.profile %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}" style="text-decoration:none">
                        edit
                    </a>
                {% endif %}
            </h5>
            <h6>
                {{ target_user.profile.message }}
            </h6>
        {% else %}
            <img src="../../media/basic.jpg" alt="" style="height: 8rem; width: 8rem; border-radius: 10rem; margin-bottom: .5rem;">
            <a href="{% url 'profileapp:create' %}" style="text-decoration:none">
                <p>
                    {% if target_user.pk == user.pk %}
                        프로필 생성
                    {%  endif %}
                </p>
            </a>
        {% endif %}

        <br><br>

        {% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=target_user.pk %}" style="text-decoration:none">
                <p>
                    회원수정
                </p>
            </a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}" style="text-decoration:none">
                <p>
                    회원탈퇴
                </p>
            </a>
        {% endif %}
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4> 로그인 </h4>
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
        <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/main.html
{% extends 'base.html' %}

{% block contents %}
<div>
    <div style="text-align:center">
        <p>
            <h1>메인화면</h1>
        </p>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/success.html
{% extends 'base.html' %}

{% block contents %}
<div>
    <div style="text-align:center">
        <p>
            <h1>메인화면(로그인)</h1>
        </p>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4> 회원수정 </h4>
    </div>
<div style="text-align:center">
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <p></p>
        <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>

</div>
</div>
{% endblock %}