account/urls.py
from django.conf.urls import url
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:form_id>/', views.show, name='show'),
]

accountapp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

commentapp/urls.py
from django.urls import path
from commentapp.views import CommentCreateView, CommentDeleteView


app_name = "commentapp"

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from snsProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models
from articleapp.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now=True)

commentapp/forms.py
from django.forms import ModelForm
from commentapp.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

commentapp/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView
from articleapp.models import Article
from commentapp.forms import CommentCreationForm
from commentapp.models import Comment


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.article.pk})


class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.article.pk})

commentapp/templates/commentapp/create.html
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 300px; margin: 4rem auto">
    <form action="{% url 'commentapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if user.is_authenticated %}
            <input type="submit" class="btn btn-secondary active rounded-pill col-6 mt-3">
        {% else %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="btn btn-primary active rounded-pill col-6 mt-3">
                Login
            </a>
        {% endif %}

        <input type="hidden" name="article_pk" value="{{ article.pk }}">
    </form>
</div>
{% endblock %}

commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}

{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 2rem auto">
    <div class="mb-4" style="font-size: .8rem; color: #050505">
        아래 제목의 Comment를 삭제합니다. 맞으면 삭제버튼을 클릭하세요.<P></P>
        <span style="background-color: black; font-size: 1.4rem; color: white">&nbsp&nbsp{{ target_comment.댓글쓰기 }}&nbsp&nbsp</span>
    </div>
    <div>
        <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="삭제" class="btn btn-danger rounded-pill col-6 mt-1">
        </form>
    </div>
</div>
{% endblock %}

commentapp/templates/commentapp/detail.html
<div style="border: 1px dotted; width: 100%; height: 70px; text-align: left; padding: 1%; margin: 1rem 0;
    border-radius: 1rem; border-color: #bbb;">
    <div>
        <span style="font-size: .9rem; color: #050505">
            <img src="{{ comment.writer.profile.image.url }}" alt="" style="height: 1.5rem; width: 1.5rem; border-radius: 1.5rem; ">
            {{ comment.writer.profile.nickname }}
        </span>
        &nbsp&nbsp&nbsp
        <span style="font-size: .8rem; color: #385185">
            {{ comment.created_at }}
        </span>
    </div>
    <div style="font-size: 15px; color: #565656; margin: .6rem 0;">
        &nbsp&nbsp&nbsp
        {{ comment.content }}
        {% if comment.writer == user %}
        <div style="font-size: .5rem; text-align: right; margin: -1.7rem 0">
            <a href="{% url 'commentapp:delete' pk=comment.pk %}" style="font-size: .5rem;" class="btn btn-sm btn-secondary active rounded-pill mb-3">
                삭제
            </a>
        </div>
        {% endif %}
    </div>
</div>