account/urls.py
from django.conf.urls import url
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:form_id>/', views.show, name='show'),
]

articleapp/urls.py
from django.urls import path
from articleapp import views
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView


app_name = "articleapp"

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('<int:pk>/like', views.like, name='like'),
    path('<int:pk>/dislike', views.dislike, name='dislike'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from snsProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_created=True, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_articles')

articleapp/forms.py
from django.forms import ModelForm
from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin
from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


has_decorator = [login_required, article_ownership_required]


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'
    success_url = reverse_lazy('articleapp:list')
    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 15


def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articleapp:detail',article.pk)

def dislike(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user in article.dislike_users.all():
        article.dislike_users.remove(request.user)
    else:
        article.dislike_users.add(request.user)
    return redirect('articleapp:detail',article.pk)

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 300px; margin: 4rem auto">
    <div class="mb-4">
        <h4> Article 생성 </h4>
    </div>
    <div>
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 2rem auto">
    <div class="mb-4" style="font-size: .8rem; color: #050505">
        아래 제목의 article을 삭제합니다. 맞으면 삭제버튼을 클릭하세요.<P></P>
        <span style="background-color: black; font-size: 1.4rem; color: white">&nbsp&nbsp{{ target_article.title }}&nbsp&nbsp</span>
    </div>
    <div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="삭제" class="btn btn-danger rounded-pill col-6 mt-1">
        </form>
    </div>
</div>
{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block contents %}

<div>
    <div style="text-align: center; max-width: 700px; margin: 1rem auto">
        <h2>
            {{ target_article.title }}
        </h2>
            {{ target_article.writer.profile.nickname }}
        <hr>
        <h6>
            <img src="{{ target_article.image.url }}" alt="" style="width: 450px; cursor: pointer;"
            onclick="doImgPop('{{ target_article.image.url }}')">
        </h6>

        {{ target_article.content }}

                <br><hr>

        {% if target_article.writer == user %}
        <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-primary rounded-pill col-1 mt-3 mb-3">
                Article 수정
        </a>
        <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-danger rounded-pill col-1 mt-3 mb-3">
                Article 삭제
        </a>
        {% endif %}
        <br>
        {% if not user.is_authenticated %}
            <i class="far fa-thumbs-up fa-lg animated infinite bounce delay-1s" style="font-size: 1rem; color:gray;">
            </i>
            {{ target_article.like_users.count }}
            <i class="far fa-thumbs-down fa-lg animated infinite bounce delay-1s" style="font-size: 1rem; color:gray;">
            </i>
            {{ target_article.like_users.count }}
        {% else %}
            {% if request.user in target_article.like_users.all %}
                <a href="{% url 'articleapp:like' target_article.pk %}" style="text-decoration: none">
                    <i class="far fa-thumbs-up fa-lg animated infinite bounce delay-1s"
                       style="font-size: 1rem; color:red;">
                    </i>
                </a>
                <span style="font-size: .8rem">{{ target_article.like_users.count }}</span>
            {% else %}
                <a href="{% url 'articleapp:like' target_article.pk %}" style="text-decoration: none">
                    <i class="far fa-thumbs-up fa-lg animated infinite bounce delay-1s"
                       style="font-size: 1rem; color:gray;">
                    </i>
                </a>
                <span style="font-size: .8rem">{{ target_article.like_users.count }}</span>
            {% endif %}

            {% if request.user in target_article.dislike_users.all %}
                <a href="{% url 'articleapp:dislike' target_article.pk %}" style="text-decoration: none">
                    <i class="far fa-thumbs-down fa-lg animated infinite bounce delay-1s"
                       style="font-size: 1rem; color:blue;">
                    </i>
                </a>
                <span style="font-size: .8rem">{{ target_article.dislike_users.count }}</span>
            {% else %}
                <a href="{% url 'articleapp:dislike' target_article.pk %}" style="text-decoration: none">
                    <i class="far fa-thumbs-down fa-lg animated infinite bounce delay-1s"
                       style="font-size: 1rem; color:gray;">
                    </i>
                </a>
                <span style="font-size: .8rem">{{ target_article.dislike_users.count }}</span>
            {% endif %}
        {% endif %}
    </div>
    {% for comment in target_article.comment.all %}
        {% include 'commentapp/detail.html' with comment=comment %}
    {% endfor %}
    {% include 'commentapp/create.html' with article=target_article %}
</div>

<script>
function doImgPop(img){
    img1= new Image();
    img1.src=(img);
    imgControll(img);
}

function imgControll(img){
    if((img1.width!=0)&&(img1.height!=0)){
        viewImage(img);
    }
    else{
        controller="imgControll('"+img+"')";
        intervalID=setTimeout(controller,20);
    }
}

function viewImage(img){
    W=img1.width;
    H=img1.height;
    O="width="+W+",height="+H+",scrollbars=no";
    imgWin=window.open("","",O);
    imgWin.document.write("<html><head><title>{{ target_article.title }}</title></head>");
    imgWin.document.write("<body topmargin=0 leftmargin=0></body>");
    imgWin.document.write("<img src="+img+" onclick='self.close()' style='cursor:pointer;' title ='클릭하시면 창이 닫힙니다.'>");
    imgWin.document.close();
}
</script>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}
<style>
  .container div {
  width: 250px;
  background-color: antiquewhite;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 1rem;
}
  .container img {
    width: 100%;
    border-radius: 1rem;
  }

</style>

<div class="container">
    {% for article in article_list %}
    <a href="{% url 'articleapp:detail' pk=article.pk %}">
        {% include  'snippets/card.html' with article=article %}
    </a>
    {% endfor %}
</div>

<br>
<center>
    {% if user.is_authenticated %}
    <a href="{% url 'articleapp:create' %}" class="btn btn-secondary rounded-pill col-1 mt-3 mb-3">
            Article 생성
    </a>
    {% endif %}
</center>

{% include 'snippets/pagination.html' with page_obj=page_obj %}

<script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 300px; margin: 4rem auto">
    <div class="mb-4">
        <h4> Article 수정 </h4>
    </div>
    <div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-secondary active rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}